language: ruby
cache: bundler
sudo: false

before_install:
- openssl aes-256-cbc -K $encrypted_c98ef108ab21_key -iv $encrypted_c98ef108ab21_iv
  -in berniedurfee-ge.txt -out berniedurfee-ge.pem -d

deploy:
  provider: chef-supermarket
  user_id: berniedurfee-ge
  client_key: berniedurfee-ge.pem
  cookbook_category: Other
